name: Main
run-name: Build & test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarqube:
    name: SonarQube
    uses: mb-dot-dev/reusable-workflows/.github/workflows/python-test-sonar.yaml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
